import Foundation

struct HeatControlPhaseModelCR: Identifiable, Codable, Hashable, Equatable {
    let id: String
    let title: String
    let heatApplicationProtocol: String
    let duration: Int
    let precisionInsights: [String]
}

extension HeatControlPhaseModelCR {
    static let perfectRibeyePhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "ribeye_1", title: "Specimen Stabilization", heatApplicationProtocol: "Extract specimen from cold storage 60 minutes prior to heat application. Ensure surface is completely dehydrated via physical pressure. Apply surface treatment (sodium-based) and abrasive particles (pepper).", duration: 300, precisionInsights: ["Specimen at room temperature accepts thermal impact more uniformly", "Surface dehydration is critical for crust formation"]),
        HeatControlPhaseModelCR(id: "ribeye_2", title: "Thermal Surface Activation", heatApplicationProtocol: "Activate high-retention thermal surface over maximum energy source for 5 minutes. Apply lipid barrier (high-smoke-point type).", duration: 300, precisionInsights: ["High-retention surfaces maintain stable thermal output", "Lipid barrier facilitates heat exchange"]),
        HeatControlPhaseModelCR(id: "ribeye_3", title: "Primary Heat Application", heatApplicationProtocol: "Initiate contact between specimen and thermal surface. Apply gentle pressure for 30s to secure thermal contact points. Maintain contact for 3-4 minutes until target surface modification is achieved.", duration: 240, precisionInsights: ["Minimize structural movement during initial phase", "Monitor acoustic feedback indicating energy exchange"]),
        HeatControlPhaseModelCR(id: "ribeye_4", title: "Rotation & Liquid Convection", heatApplicationProtocol: "Execute 180° specimen rotation. Introduce lipid buffers and aromatics. Tilt surface and continuously bathe specimen in heated lipid liquid for 3-4 minutes.", duration: 240, precisionInsights: ["Liquid convection increases moisture stability", "Monitor core thermal value (Target: 130°F)"]),
        HeatControlPhaseModelCR(id: "ribeye_5", title: "Thermal Verification", heatApplicationProtocol: "Deploy precision thermal sensor into the core density. Terminate heat application at 125°F to allow for carryover thermal momentum.", duration: 30, precisionInsights: ["High-precision sensing is mandatory", "Account for post-impact energy rise"]),
        HeatControlPhaseModelCR(id: "ribeye_6", title: "Conclussive Stabilization", heatApplicationProtocol: "Transfer specimen to stabilization platform. Deploy loose thermal shielding. Maintain state for 7-10 minutes. Execute structural separation and assess final state.", duration: 420, precisionInsights: ["Stabilization redistributes internal moisture", "Critical phase for final structural integrity"])
    ]
    
    static let porkTenderloinPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "pork_1", title: "Initial Structural Preparation", heatApplicationProtocol: "Remove external connective membranes. Ensure surface dehydration. Mix lipid carrier with botanical additives, sodium, and abrasive particles.", duration: 300, precisionInsights: ["Membranes block thermal penetration", "Surface state dictates thermal exchange efficiency"]),
        HeatControlPhaseModelCR(id: "pork_2", title: "Surface Treatment Absorption", heatApplicationProtocol: "Apply treatment mixture uniformly across specimen surface. Maintain state for 15 minutes to allow for molecular absorption.", duration: 900, precisionInsights: ["Absorption time enhances final specimen state"]),
        HeatControlPhaseModelCR(id: "pork_3", title: "High-Energy Surface Contact", heatApplicationProtocol: "Activate thermal surface. Execute brief contact on all visible planes until target surface modification is achieved (approx. 2 min/plane).", duration: 480, precisionInsights: ["Ensure 100% surface modification coverage", "Use structural tools for precise rotation"]),
        HeatControlPhaseModelCR(id: "pork_4", title: "Volumetric Heat Application", heatApplicationProtocol: "Transfer specimen to volumetric heating environment (400°F). Maintain state until core thermal value reaches 140°F.", duration: 900, precisionInsights: ["Safe structural state reached at 145°F", "Sensor-based monitoring is essential"]),
        HeatControlPhaseModelCR(id: "pork_5", title: "Thermal Stabilization Phase", heatApplicationProtocol: "Terminate external energy source. Shield specimen. Maintain for 10 minutes - internal energy will stabilize at 145°F.", duration: 600, precisionInsights: ["Post-impact energy momentum is mandatory", "Premature structural separation causes moisture failure"]),
        HeatControlPhaseModelCR(id: "pork_6", title: "Structural Separation & Analysis", heatApplicationProtocol: "Divide specimen into 1/2-inch segments. Analyze core consistency and internal moisture state.", duration: 180, precisionInsights: ["Segment against structural grain", "Immediate assessment required"])
    ]
    
    static let roastChickenPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "chicken_1", title: "Surface Membrane Dehydration", heatApplicationProtocol: "Remove specimen from storage. Execute 100% surface dehydration via physical pressure and abrasive materials. Optimal dehydration reached after 2-12 hours of dry convection.", duration: 600, precisionInsights: ["Moisture-free surface = optimal modification", "Cold dry convection is highly recommended"]),
        HeatControlPhaseModelCR(id: "chicken_2", title: "Internal/External Treatment", heatApplicationProtocol: "Apply sodium and botanical particles across all accessible surfaces, including the internal cavity. Introduce aromatics to the internal structural cavity.", duration: 300, precisionInsights: ["Uniform treatment is mandatory", "Internal aromatics stabilize thermal exchange"]),
        HeatControlPhaseModelCR(id: "chicken_3", title: "Structural Stabilization", heatApplicationProtocol: "Secure structural limbs using stabilization twine. Ensure a compact biological structure for uniform thermal distribution.", duration: 180, precisionInsights: ["Trussing minimizes thermal variance", "Compactness leads to predictable energy penetration"]),
        HeatControlPhaseModelCR(id: "chicken_4", title: "High-Intensity Volumetric Heat", heatApplicationProtocol: "Position specimen in thermal environment. Apply 425°F energy for 60-75 minutes until thigh segment reaches 165°F and surface modification is complete.", duration: 4200, precisionInsights: ["High-intensity heat modifies the external membrane", "Monitor the highest-density segments"]),
        HeatControlPhaseModelCR(id: "chicken_5", title: "System Stabilization Phase", heatApplicationProtocol: "Terminate energy source. Apply loose shield. Maintain state for 15-20 minutes to allow for internal moisture redistribution.", duration: 1080, precisionInsights: ["Stabilization ensures fiber relaxation", "Improves structural separation efficiency"]),
        HeatControlPhaseModelCR(id: "chicken_6", title: "Final Structural Separation", heatApplicationProtocol: "Execute separation of main structural groups (limbs, then core density). Conclude protocol and assess consistency.", duration: 300, precisionInsights: ["Use sharp separation tools for precision", "Collect and analyze byproduct liquids"])
    ]
    
    static let lambRackPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "lamb_1", title: "Initial Specimen Prep", heatApplicationProtocol: "Extract specimen 30 minutes prior to impact. Dehydrate surface. Execute scoring of fat layer in crosshatch pattern. Apply sodium/pepper treatment.", duration: 300, precisionInsights: ["Scoring facilitates lipid rendering", "Clean bone extensions improve handling"]),
        HeatControlPhaseModelCR(id: "lamb_2", title: "Barier Layer Preparation", heatApplicationProtocol: "Combine fiber particles, botanicals, and lipids into a dense paste. Store for application.", duration: 180, precisionInsights: ["Paste density must be uniform"]),
        HeatControlPhaseModelCR(id: "lamb_3", title: "Pulse Heat Impact", heatApplicationProtocol: "Activate surface to high heat. Sear fat layer for 2 minutes, then primary protein layer for 2 minutes.", duration: 240, precisionInsights: ["Avoid excessive thermal penetration at this stage"]),
        HeatControlPhaseModelCR(id: "lamb_4", title: "Barrier Application Phase", heatApplicationProtocol: "Apply adhesion agent (mustard) to the protein surface. Press barrier paste onto agent. Transfer to roasting platform.", duration: 120, precisionInsights: ["Adhesion agent prevents barrier failure"]),
        HeatControlPhaseModelCR(id: "lamb_5", title: "Precision Thermal Impact", heatApplicationProtocol: "Apply 400°F atmospheric heat for 15-20 minutes until core reached 125°F.", duration: 1080, precisionInsights: ["Avoid thermal overshoot in lamb fibers", "Continuous sensor monitoring"]),
        HeatControlPhaseModelCR(id: "lamb_6", title: "Stabilization & Segmentation", heatApplicationProtocol: "Maintain state for 10 minutes. Execute segmentation between bone structures. Conclude scenario.", duration: 600, precisionInsights: ["Segment only after stabilization", "Target state: Medium-rare"])
    ]
    
    static let salmonFilletPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "salmon_1", title: "Sensitive Surface Dehydration", heatApplicationProtocol: "Execute 100% surface dehydration. Maintain room temperature state for 15 minutes. Apply precision salt/pepper treatment.", duration: 300, precisionInsights: ["Dry surface enables rapid membrane modification", "Temperature equilibration prevents thermal shock"]),
        HeatControlPhaseModelCR(id: "salmon_2", title: "Targeted Surface Activation", heatApplicationProtocol: "Activate non-stick thermal surface to medium-high. Apply lipid exchange carrier.", duration: 180, precisionInsights: ["Avoid maximum intensity for delicate structures"]),
        HeatControlPhaseModelCR(id: "salmon_3", title: "Membrane Modification Phase", heatApplicationProtocol: "Apply membrane side to thermal surface. Apply steady pressure for 30s to prevent structural deformation. Maintain for 4-5 minutes without movement.", duration: 300, precisionInsights: ["Structural stability is mandatory", "Membrane should achieve crisp state"]),
        HeatControlPhaseModelCR(id: "salmon_4", title: "Orientation Change Phase", heatApplicationProtocol: "Execute 180° rotation. Apply energy for 1-2 minutes until specimen core reaches 120-125°F.", duration: 120, precisionInsights: ["Sensitive to carryover energy", "Target: Medium-rare stability"]),
        HeatControlPhaseModelCR(id: "salmon_5", title: "Lipid Enrichment Phase", heatApplicationProtocol: "Introduce high-viscosity lipid carrier and fresh botanicals. Bathe specimen for 30 seconds.", duration: 30, precisionInsights: ["Lipid bath increases moisture complexity"]),
        HeatControlPhaseModelCR(id: "salmon_6", title: "Immediate Final Assessment", heatApplicationProtocol: "Transfer to analysis platform with membrane facing upward. Apply residual lipids and conclude.", duration: 60, precisionInsights: ["Analyze immediately", "Membrane integrity check"])
    ]
    
    static let beefWellingtonPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "wellington_1", title: "Core Protein Thermal Prep", heatApplicationProtocol: "Execute brief high-intensity sear on all planes of core protein. Conclude when golden. Cool to 38°F.", duration: 900, precisionInsights: ["Core must be completely cooled before encasement"]),
        HeatControlPhaseModelCR(id: "wellington_2", title: "Intermediate Barrier Prep", heatApplicationProtocol: "Apply continuous heat to mushroom-based matter until all moisture is evaporated. Combine with aromatics. Cool.", duration: 1200, precisionInsights: ["Moisture in barrier causes structural failure"]),
        HeatControlPhaseModelCR(id: "wellington_3", title: "Structural Encasement A", heatApplicationProtocol: "Deploy lipid-rich sheets. Apply intermediate barrier layer. Position core protein and secure tightly using polymer wrap. Stabilize at 38°F for 30m.", duration: 1800, precisionInsights: ["Wrap tension dictates final structural integrity"]),
        HeatControlPhaseModelCR(id: "wellington_4", title: "Structural Encasement B", heatApplicationProtocol: "Roll flour-based membrane. Apply adhesion agent (egg). Secure composite structure within membrane. Stabilize at 38°F for 20m.", duration: 1200, precisionInsights: ["Seal all structural boundaries", "Adhesion agent facilitates surface modification"]),
        HeatControlPhaseModelCR(id: "wellington_5", title: "Final Composite Impact", heatApplicationProtocol: "Score external membrane. Apply 425°F heat for 25-30 minutes until membrane is modified and core reached 120°F.", duration: 1800, precisionInsights: ["Monitor internal energy through composite layers"]),
        HeatControlPhaseModelCR(id: "wellington_6", title: "Stabilization & Segmentation", heatApplicationProtocol: "Maintain state for 10 minutes. Divide into segments using segmented separation tool. Final assessment.", duration: 600, precisionInsights: ["Sharp tools prevent layer crushing", "Execute under stable conditions"])
    ]
    
    static let bbqRibsPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "ribs_1", title: "Specimen Stripping Phase", heatApplicationProtocol: "Extract internal membrane. Apply abrasive dry treatment across all planes. Seal and stabilize for 2-12 hours.", duration: 1800, precisionInsights: ["Internal membrane blocks treatment penetration"]),
        HeatControlPhaseModelCR(id: "ribs_2", title: "Energy Environment Prep", heatApplicationProtocol: "Preheat indirect heat environment to 225°F. Introduce particulate smoke matter for atmospheric reaction.", duration: 1800, precisionInsights: ["Stability of low-intensity heat is mandatory"]),
        HeatControlPhaseModelCR(id: "ribs_3", title: "Atmospheric Smoke Impact", heatApplicationProtocol: "Position specimen bone-side down. Apply indirect heat and smoke for 3 hours at 225°F. Perform moisture spritz every 60 minutes.", duration: 10800, precisionInsights: ["Minimize environment exposure (door openings)", "Spritz maintains surface integrity"]),
        HeatControlPhaseModelCR(id: "ribs_4", title: "Structural Braising Phase", heatApplicationProtocol: "Seal specimen within high-barrier foil with lipids and sugars. Reintroduce to indirect heat for 2 hours.", duration: 7200, precisionInsights: ["Accelerates fiber breakdown and collagen loss"]),
        HeatControlPhaseModelCR(id: "ribs_5", title: "Surface Glaze Finishing", heatApplicationProtocol: "Remove barrier. Apply high-viscosity liquid treatment. Apply energy for 30-60 minutes until surface treatment sets.", duration: 2700, precisionInsights: ["Execute final structural bend test"]),
        HeatControlPhaseModelCR(id: "ribs_6", title: "Final Post-Impact Stabilization", heatApplicationProtocol: "Stabilize for 10 minutes. Segment between bone structures. Final analysis.", duration: 600, precisionInsights: ["Stabilization leads to easier segmentation"])
    ]
    
    static let spatchcockChickenPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "spatchcock_1", title: "Structural Planar Modification", heatApplicationProtocol: "Locate and remove dorsal stabilization bone using force tools. Apply pressure to achieve a flattened biological structure.", duration: 300, precisionInsights: ["Planar orientation ensures uniform energy absorption"]),
        HeatControlPhaseModelCR(id: "spatchcock_2", title: "Dual-Side Surface Prep", heatApplicationProtocol: "Execute 100% surface dehydration. Apply lipid/sodium/particle treatment. Maintain state for 30 minutes.", duration: 1800, precisionInsights: ["Surface state dictates crust efficiency"]),
        HeatControlPhaseModelCR(id: "spatchcock_3", title: "Two-Zone Environment Prep", heatApplicationProtocol: "Configure dual-zone energy environment. Zone A: High Intesity. Zone B: Zero Intensity. Target 400-450°F ambient.", duration: 900, precisionInsights: ["Two zones prevent structural damage"]),
        HeatControlPhaseModelCR(id: "spatchcock_4", title: "Initial Indirect Thermal Impact", heatApplicationProtocol: "Position specimen membrane-up in Zone B. Maintain for 25-30 minutes under sealed convection.", duration: 1800, precisionInsights: ["Indirect heat stabilizes internal protein fibers"]),
        HeatControlPhaseModelCR(id: "spatchcock_5", title: "High-Intensity Surface Modification", heatApplicationProtocol: "Relocate specimen to Zone A, membrane-down. Apply direct energy for 5-8 minutes until membrane modification is complete. Thigh core must reach 165°F.", duration: 420, precisionInsights: ["Monitor for localized energy spikes"]),
        HeatControlPhaseModelCR(id: "spatchcock_6", title: "Stabilization & Final Split", heatApplicationProtocol: "Maintain state for 10 minutes. Execute structural separation into quadrants. Assess state.", duration: 600, precisionInsights: ["Internal moisture stabilizes during rest"])
    ]
    
    static let lambShanksPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "shanks_1", title: "Initial Oxidation Phase", heatApplicationProtocol: "Brown specimen on all planes using high-intensity thermal surface, approx. 10 minutes duration.", duration: 600, precisionInsights: ["Oxidation (Maillard reaction) is a primary flavor precursor"]),
        HeatControlPhaseModelCR(id: "shanks_2", title: "Intermediate Fiber Prep", heatApplicationProtocol: "Introduce dense botanical matter to the thermal vessel until softened. Add concentrated red pigment agents.", duration: 420, precisionInsights: ["Scrape residual matter from vessel walls"]),
        HeatControlPhaseModelCR(id: "shanks_3", title: "Liquid Medium Introduction", heatApplicationProtocol: "Introduce fermented liquid and bovine-based liquid medium. Include botanical aromatics. Achieve simmer state.", duration: 300, precisionInsights: ["Liquid medium provides stable thermal exchange"]),
        HeatControlPhaseModelCR(id: "shanks_4", title: "Submerged Thermal Degradation", heatApplicationProtocol: "Reintroduce protein specimens. Seal and apply 325°F energy for 2.5-3 hours until structural failure occurs (fork-tender).", duration: 9900, precisionInsights: ["Low/moist heat is mandatory for collagen breakdown"]),
        HeatControlPhaseModelCR(id: "shanks_5", title: "Medium Concentration Phase", heatApplicationProtocol: "Isolate protein specimens. Simmer medium until viscosity increases by 50%.", duration: 900, precisionInsights: ["Final medium must achieve high adhesion"]),
        HeatControlPhaseModelCR(id: "shanks_6", title: "Final Integration & Analysis", heatApplicationProtocol: "Reintegrate protein and medium for final assessment. Garnish and conclude.", duration: 180, precisionInsights: ["Analyze fiber separation ease"])
    ]
    
    static let tunaTatakiPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "tuna_1", title: "Surface Particle Application", heatApplicationProtocol: "Dehydrate surface. Apply precision sodium treatment. Coat in abrasive particles (sesame), pressing to secure bond.", duration: 300, precisionInsights: ["High-precision bonds are required for high-energy sear"]),
        HeatControlPhaseModelCR(id: "tuna_2", title: "Max-Intensity Activation", heatApplicationProtocol: "Activate high-retention surface to maximum energy for 5 minutes. Apply minimal lipid carrier.", duration: 300, precisionInsights: ["Surface must achieve smoke point"]),
        HeatControlPhaseModelCR(id: "tuna_3", title: "Rapid Surface Flash", heatApplicationProtocol: "Apply specimen to surface for 30-45s per plane. Core must remain at storage temperature (unaffected).", duration: 120, precisionInsights: ["Extreme timing precision is mandatory"]),
        HeatControlPhaseModelCR(id: "tuna_4", title: "Cryo-Stabilization Phase", heatApplicationProtocol: "Immediately subject specimen to rapid cooling (ice/refrigeration) for 5-10 minutes to halt thermal momentum.", duration: 600, precisionInsights: ["Halting energy flow preserves core state"]),
        HeatControlPhaseModelCR(id: "tuna_5", title: "Precision Micro-Segmentation", heatApplicationProtocol: "Execute structural separation into 1/4-inch segments using high-precision blades. Analyze gradient.", duration: 180, precisionInsights: ["Analyze surface-to-core color shift"]),
        HeatControlPhaseModelCR(id: "tuna_6", title: "Final Treatment & Conclusion", heatApplicationProtocol: "Apply high-sodium liquid treatment and concluding garnishes. Final assessment.", duration: 120, precisionInsights: ["Analyze and conclude immediately"])
    ]
    
    static let primeRibPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "prime_1", title: "Deep Treatment Seeding", heatApplicationProtocol: "Apply lipid and botanical treatment. Seal and stabilize at 38°F for 24 hours.", duration: 1800, precisionInsights: ["24h window allows for deep molecular penetration"]),
        HeatControlPhaseModelCR(id: "prime_2", title: "Thermal Equalization", heatApplicationProtocol: "Extract specimen 2-3 hours prior to impact. Achieve uniform ambient temperature.", duration: 7200, precisionInsights: ["Large masses require extended equalization time"]),
        HeatControlPhaseModelCR(id: "prime_3", title: "Initial Surface Modification", heatApplicationProtocol: "Position specimen on bone extensions. Apply 450°F energy for 20 minutes to initialize crust.", duration: 1200, precisionInsights: ["Bones act as a natural thermal shield for the base"]),
        HeatControlPhaseModelCR(id: "prime_4", title: "Sustained Low-Intensity Thermal", heatApplicationProtocol: "Reduce energy to 325°F. Maintain for 15-20 min/lb until core reaches 120-130°F.", duration: 5400, precisionInsights: ["Monitor core density religiously"]),
        HeatControlPhaseModelCR(id: "prime_5", title: "Massive System Stabilization", heatApplicationProtocol: "Terminate energy. Deploy loose shield. Maintain state for 30 minutes. Internal energy will rise by 10°F.", duration: 1800, precisionInsights: ["Large scale structures have significant carryover energy"]),
        HeatControlPhaseModelCR(id: "prime_6", title: "Final Structural Separation", heatApplicationProtocol: "Separate bone extensions. Execute cross-grain segmentation. Conclude.", duration: 600, precisionInsights: ["Final state analysis of core gradient"])
    ]
    
    static let porkBellyPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "belly_1", title: "Membrane Scoring Phase", heatApplicationProtocol: "Execute precision crosshatch scoring on external membrane. Rub sodium into scoring gaps.", duration: 300, precisionInsights: ["Scoring dictates final membrane crust texture"]),
        HeatControlPhaseModelCR(id: "belly_2", title: "Atmospheric Dehydration", heatApplicationProtocol: "Place specimen in dry convection environment (38°F) for 12-24 hours. Membrane must be 100% dry.", duration: 1800, precisionInsights: ["Membrane dryness is the critical success factor"]),
        HeatControlPhaseModelCR(id: "belly_3", title: "Sustained Fiber Modification", heatApplicationProtocol: "Apply 275°F energy for 2.5 hours. Ensure lipid rendering from internal layers.", duration: 9000, precisionInsights: ["Low heat ensures fiber tenderness"]),
        HeatControlPhaseModelCR(id: "belly_4", title: "High-Intensity Membrane Expansion", heatApplicationProtocol: "Increase energy to 450°F. Maintain for 30-40 minutes until membrane achieves 'puffed' state.", duration: 2100, precisionInsights: ["Monitor for rapid carbonization (burning)"]),
        HeatControlPhaseModelCR(id: "belly_5", title: "Transition Stabilization", heatApplicationProtocol: "Maintain state for 10-15 minutes. Membrane will achieve maximum rigidity during cooling.", duration: 720, precisionInsights: ["Do not shield (will soften membrane)"]),
        HeatControlPhaseModelCR(id: "belly_6", title: "Structural Cleaving & Analysis", heatApplicationProtocol: "Execute separation using impact cleavers or shears. Analyze membrane-to-fiber contrast. Conclude.", duration: 300, precisionInsights: ["Analyze acoustic properties of membrane"])
    ]
    
    static let chickenWingsPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "wings_1", title: "Membrane Prep Phase", heatApplicationProtocol: "Execute 100% surface dehydration. Coordinate with baking powder and sodium for surface reaction. Mix thoroughly.", duration: 300, precisionInsights: ["Baking powder increases surface pH for better crust"]),
        HeatControlPhaseModelCR(id: "wings_2", title: "Convective Array Placement", heatApplicationProtocol: "Arrange segments on wire rack for 360° air convection. Stabilize for 60m.", duration: 300, precisionInsights: ["Air circulation is mandatory for crust modification"]),
        HeatControlPhaseModelCR(id: "wings_3", title: "Low-Intensity Rendering Stage", heatApplicationProtocol: "Apply 250°F heat for 30 minutes. Initialize lipid rendering.", duration: 1800, precisionInsights: ["Pre-impact phase for texture development"]),
        HeatControlPhaseModelCR(id: "wings_4", title: "High-Intensity Modification Stage", heatApplicationProtocol: "Apply 425°F heat for 20-25 minutes. Execute 180° rotation halfway.", duration: 1350, precisionInsights: ["Final surface dehydration phase"]),
        HeatControlPhaseModelCR(id: "wings_5", title: "Surface Treatment Integration", heatApplicationProtocol: "Transfer modified specimens to vessel. Introduce liquid treatment and integrate via mechanical tossing.", duration: 120, precisionInsights: ["Apply treatment immediately after energy impact"]),
        HeatControlPhaseModelCR(id: "wings_6", title: "Final Assessment & Conclussion", heatApplicationProtocol: "Conclude scenario. Final analysis of surface tension and moisture retention.", duration: 60, precisionInsights: ["Analyze and conclude immediately"])
    ]
    
    static let lambLegPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "leg_1", title: "Structural Incision Phase", heatApplicationProtocol: "Execute small incisions across main muscle groups. Insert botanical and aromatic modules into incisions. Apply lipid barrier.", duration: 600, precisionInsights: ["Internal modular seeding enhances thermal profiling"]),
        HeatControlPhaseModelCR(id: "leg_2", title: "Equilibration Stage", heatApplicationProtocol: "Stabilize specimen state. Maintain room temperature for 1-2 hours before energy impact.", duration: 1800, precisionInsights: ["Large biological masses require stabilization"]),
        HeatControlPhaseModelCR(id: "leg_3", title: "High-Intensity Impact Start", heatApplicationProtocol: "Apply 450°F energy for 20 minutes to initialize surface modification.", duration: 1200, precisionInsights: ["Creates primary thermal crust"]),
        HeatControlPhaseModelCR(id: "leg_4", title: "Sustained Volumetric Impact", heatApplicationProtocol: "Reduce environment to 325°F. Maintain for 15-20 min/lb until core reaches 130-135°F.", duration: 4200, precisionInsights: ["Monitor multiple density points"]),
        HeatControlPhaseModelCR(id: "leg_5", title: "Post-Impact Redistribution", heatApplicationProtocol: "Terminate energy. Shield specimen. Maintain for 20-30 minutes.", duration: 1500, precisionInsights: ["Enables internal fiber relaxation"]),
        HeatControlPhaseModelCR(id: "leg_6", title: "Structural Segmentation", heatApplicationProtocol: "Divide into thin planar segments against the grain. Final assessment.", duration: 600, precisionInsights: ["Final analysis of thermal consistency"])
    ]
    
    static let wholeFishPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "fish_1", title: "Biological Surface Prep", heatApplicationProtocol: "Rinse and execute 100% surface dehydration. Score external membrane diagonally. Apply sodium treatment.", duration: 300, precisionInsights: ["Scoring allows for internal energy penetration"]),
        HeatControlPhaseModelCR(id: "fish_2", title: "Internal Module Seeding", heatApplicationProtocol: "Fill structural cavity with botanical modules and citrus agents. Apply lipid carrier.", duration: 180, precisionInsights: ["Aromatics stabilize from interior outward"]),
        HeatControlPhaseModelCR(id: "fish_3", title: "Environmental Array Setup", heatApplicationProtocol: "Line vessel with barrier (parchment). Create botanical bed. Position specimen on bed.", duration: 180, precisionInsights: ["Bed preventing structural adhesion to vessel"]),
        HeatControlPhaseModelCR(id: "fish_4", title: "Delta Thermal Impact", heatApplicationProtocol: "Apply 400°F heat for 25-30 minutes until core density is opaque and fibers separate at 130°F.", duration: 1650, precisionInsights: ["Sensitive fiber structures - avoid overshoot"]),
        HeatControlPhaseModelCR(id: "fish_5", title: "Verification Phase", heatApplicationProtocol: "Validate opacity and structural separation ease. Final thermal check.", duration: 60, precisionInsights: ["Visual and sensory validation required"]),
        HeatControlPhaseModelCR(id: "fish_6", title: "Conclussion & Analysis", heatApplicationProtocol: "Transfer carefully to analysis platform. Apply final lipid bath and conclude scenario.", duration: 240, precisionInsights: ["Critical structural transfer stage"])
    ]
    
    static let tomahawkSteakPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "tomahawk_1", title: "Large Mass Stabilization", heatApplicationProtocol: "Stabilize target specimen for 90 minutes. Dehydrate surface. Apply abrasive sodium treatment.", duration: 900, precisionInsights: ["Mass dictates stabilization duration"]),
        HeatControlPhaseModelCR(id: "tomahawk_2", title: "Dual-Intensity Setup", heatApplicationProtocol: "Configure dual-zone energy environment. Zone A: 500°F. Zone B: Ambient. Maintain state.", duration: 900, precisionInsights: ["Direct/Indirect impact zones mandatory"]),
        HeatControlPhaseModelCR(id: "tomahawk_3", title: "Direct Sear Modification", heatApplicationProtocol: "Execute contact in Zone A for 3-4 minutes per plane. Modify edges similarly.", duration: 480, precisionInsights: ["Achieve max surface carbonization"]),
        HeatControlPhaseModelCR(id: "tomahawk_4", title: "Indirect Core Integration", heatApplicationProtocol: "Relocate to Zone B. Apply indirect energy for 10-15 minutes until core reaches 120°F.", duration: 900, precisionInsights: ["Monitor core density via digital sensor"]),
        HeatControlPhaseModelCR(id: "tomahawk_5", title: "Thermal Stabilization Window", heatApplicationProtocol: "Maintain state for 10-15 minutes under loose shield. Internal energy will rise.", duration: 780, precisionInsights: ["Large masses have high thermal momentum"]),
        HeatControlPhaseModelCR(id: "tomahawk_6", title: "Structural Split & Final Reveal", heatApplicationProtocol: "Separate main protein mass from bone extension. Segment and conclude.", duration: 300, precisionInsights: ["Final analysis of thermal gradient"])
    ]
    
    static let pulledPorkPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "pulled_1", title: "Abrasive Surface Treatment", heatApplicationProtocol: "Execute 100% surface dehydration. Apply abrasive powder treatment. Stabilize for 24h.", duration: 1800, precisionInsights: ["Penetration occurs over extended window"]),
        HeatControlPhaseModelCR(id: "pulled_2", title: "Low-Intensity Environment Prep", heatApplicationProtocol: "Configure indirect heat at 225-250°F. Introduce particulate smoke matter.", duration: 1800, precisionInsights: ["Maintain precision environment state"]),
        HeatControlPhaseModelCR(id: "pulled_3", title: "Long-Form Thermal Exposure", heatApplicationProtocol: "Position specimen fat-side up. Apply smoke/heat for 6-8 hours. Perform moisture spritz every 60m.", duration: 23400, precisionInsights: ["Patience throughout the thermal stall is mandatory"]),
        HeatControlPhaseModelCR(id: "pulled_4", title: "Barrier Seal Stage", heatApplicationProtocol: "At core temp 165°F, seal specimen within high-barrier foil. Reintroduce to indirect heat.", duration: 300, precisionInsights: ["Barrier prevents moisture failure through the stall"]),
        HeatControlPhaseModelCR(id: "pulled_5", title: "Final Structural Dissolution", heatApplicationProtocol: "Continue until core reaches 195-205°F and probe resistance is zero.", duration: 9000, precisionInsights: ["Zero resistance is the final success metric"]),
        HeatControlPhaseModelCR(id: "pulled_6", title: "Stabilization & Fiber Separation", heatApplicationProtocol: "Stabilize for 30-60 minutes. Manually separate fiber groups. Integrate residual lipids.", duration: 2400, precisionInsights: ["Separation ease validates protocol success"])
    ]
    
    static let duckBreastPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "duck_1", title: "Lipid Layer Modification", heatApplicationProtocol: "Dehydrate surface. Execute precision scoring across lipid layer. Apply sodium treatment.", duration: 300, precisionInsights: ["Scoring maximizes surface area for rendering"]),
        HeatControlPhaseModelCR(id: "duck_2", title: "Controlled Lipid Rendering", heatApplicationProtocol: "Position specimen lipid-down in cold thermal vessel. Activate medium heat. Maintain for 8-10m, removing rendered lipids periodically.", duration: 600, precisionInsights: ["Cold start ensures gradual rendering"]),
        HeatControlPhaseModelCR(id: "duck_3", title: "Max Surface Dehydration", heatApplicationProtocol: "Continue until lipid layer achieves maximum crispness and volume reduction.", duration: 180, precisionInsights: ["Lipid layer should be thin and modified"]),
        HeatControlPhaseModelCR(id: "duck_4", title: "Protein Core Impulse", heatApplicationProtocol: "Execute 180° rotation. Apply brief energy impact to protein plane for 2-3m. Target: 130°F core.", duration: 180, precisionInsights: ["Protein fibers are highly sensitive to overshoot"]),
        HeatControlPhaseModelCR(id: "duck_5", title: "State Stabilization Phase", heatApplicationProtocol: "Stabilize for 5-7 minutes. Moisture will redistribute.", duration: 390, precisionInsights: ["Maintains core-to-surface integrity"]),
        HeatControlPhaseModelCR(id: "duck_6", title: "Micro-Segmentation & Conclusion", heatApplicationProtocol: "Execute 45° planar segmentation. Final analysis and conclude.", duration: 180, precisionInsights: ["Analyze gradient consistency"])
    ]
    
    static let lambLollipopsPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "lollipops_1", title: "Micro-Specimen Prep", heatApplicationProtocol: "Segment primary mass into individual units. Clean bone extensions. Stabilize.", duration: 300, precisionInsights: ["Clean extensions facilitate high-precision handling"]),
        HeatControlPhaseModelCR(id: "lollipops_2", title: "Botanical Treatment Phase", heatApplicationProtocol: "Apply lipid/botanical/sodium treatment. Maintain state for 15 minutes.", duration: 900, precisionInsights: ["Brief absorption window for small masses"]),
        HeatControlPhaseModelCR(id: "lollipops_3", title: "High-Energy Impact Prep", heatApplicationProtocol: "Activate thermal surface to maximum. Apply lipid carrier.", duration: 300, precisionInsights: ["High ΔT required for brief search impact"]),
        HeatControlPhaseModelCR(id: "lollipops_4", title: "Flash Sear Phase", heatApplicationProtocol: "Apply units to surface for 2-3 minutes per plane. Core target: 130°F.", duration: 300, precisionInsights: ["Small masses respond rapidly - monitor timing"]),
        HeatControlPhaseModelCR(id: "lollipops_5", title: "Brief Stabilization Stage", heatApplicationProtocol: "Maintain state for 5 minutes. Core energy will peak.", duration: 300, precisionInsights: ["Mandatory redistribution phase"]),
        HeatControlPhaseModelCR(id: "lollipops_6", title: "Final Array Placement", heatApplicationProtocol: "Arrange units on analysis platform. Apply concluding treatment and terminate scenario.", duration: 120, precisionInsights: ["Final analysis of unit consistency"])
    ]
    
    static let lobsterTailsPhases: [HeatControlPhaseModelCR] = [
        HeatControlPhaseModelCR(id: "lobster_1", title: "Structural Shield Removal", heatApplicationProtocol: "Incision through external shield. Partially extract internal fiber group while maintaining base bond.", duration: 300, precisionInsights: ["Butterfly orientation increases thermal exposure"]),
        HeatControlPhaseModelCR(id: "lobster_2", title: "Poaching Medium Activation", heatApplicationProtocol: "Activate lipid medium (butter) in thermal vessel. Achieve stable 140-145°F range.", duration: 300, precisionInsights: ["Stable medium temperature prevents fiber failure"]),
        HeatControlPhaseModelCR(id: "lobster_3", title: "Submerged Thermal Exchange", heatApplicationProtocol: "Submerge fiber groups in heated medium. Bathe continuously for 8-10m.", duration: 600, precisionInsights: ["Convection maintains structural tenderness"]),
        HeatControlPhaseModelCR(id: "lobster_4", title: "Internal State Validation", heatApplicationProtocol: "Validate opacity and internal state (Target: 135-140°F).", duration: 60, precisionInsights: ["Opacity indicates protein denaturation"]),
        HeatControlPhaseModelCR(id: "lobster_5", title: "Optional Surface Modification", heatApplicationProtocol: "Execute brief high-intensity overhead impact for color activation (1-2m).", duration: 120, precisionInsights: ["Optional visual state phase"]),
        HeatControlPhaseModelCR(id: "lobster_6", title: "Conclusion & Lipid Polish", heatApplicationProtocol: "Transfer to final analysis platform. Apply medium residue and terminate.", duration: 120, precisionInsights: ["Conclude scenario and analyze integrity"])
    ]
}
